# Refer to http://emanual.robotis.com/#control-table to look up the control registers for the various motors.
#
# SETUP OF REGISTERS FOR THE INTERBOTIX TURRETS
#
# All registers were left to their default values except for the ones listed here:
#   1) ID.........................The id of the Dynamixel servo. These range from 1 to 8 depending on the arm.
#   2) Baud_Rate..................The speed at which serial communication occurs. All arms have this set to 1M
#                                 baud (corresponds to a register value of '3')
#   3) Return_Delay_Time..........The amount of time the servo delays in sending a reply packet after receiving a
#                                 command packet. A value of '0' tells the servo to send a reply without any delay.
#   4) Drive_Mode:................Used to define what direction is positive rotation. A value of '0' means CCW is
#                                 positive while a value of '1' means CW is positive. It also defines if profiles are
#                                 built based on velocity or time. 'Velocity' is the default (value of '0') and 'Time'
#                                 is a value of '4'. Adding the 'direction' value to the 'profile' value gives the
#                                 appropiate register value
#   5) Velocity_Limit.............Defines the max speed of the motor. A value of '131' correpsonds to a max speed
#                                 of PI rad/s
#   6) Min_Position_Limit.........Defines the minimum limit of a joint. Values range from 0 to 4095 with 2048
#                                 being equivalent to '0' rad and 0 being '-PI' rad.
#   7) Max_Position_Limit.........Defines the maximum limit of a joint. Values range from 0 to 4095 with 2048
#                                 being equivalent to '0' rad and 4095 being 'PI' rad.
#   8) Secondary_ID...............If a joint is controlled by two motors (usually by the shoulder or elbow), one motor
#                                 can be set to follow the commands of another motor by setting this register to the ID
#                                 of the master. A value of '255' disables this.
#
# Each motor's configs are grouped under the name of the joint the motor is controlling. The names are defined at
# http://support.interbotix.com/ under the 'Specifications' section. (Click a robot and scroll down to the 'Default Joint Limits' section.)
#
# To make the process of loading and setting the configs more efficient, the 'order' sequence defines the order that the interbotix_sdk node should process the configs.
# Additionally, the 'order' sequence defines a 'group' of joints (excluding the 'gripper') that the interbotix_sdk will control at the exact same time (as opposed to
# commanding each of the joints in the group sequentially which would increase lag and not be as efficient).
#
# If your application involves controlling other joints in addition to an Interbotix Robot, place the names of those joints in the 'singles' sequence. You can then
# control these joints individually using the 'single_joint/command' topic. Note that by default, all the motors listed in the 'order' sequence (excluding 'shadow'
# motors) can be controlled individually using the above topic as well. Also note that there is no limit to the number of additional joints that can be placed in this
# sequence.
#
# Finally, the 'sleep' sequence defines the positions [rad] of each joint (in the 'order' sequence) such that the links connected to the joints are brought into a
# folded, compact state (excludes 'gripper' and 'shadow' motors if applicable).

order: [pan, tilt, tilt_shadow]
sleep: [0, 0]
singles: []

pan:
  ID: 1
  Baud_Rate: 3
  Return_Delay_Time: 0
  Drive_Mode: 0
  Velocity_Limit: 131
  Min_Position_Limit: 0
  Max_Position_Limit: 4095
  Secondary_ID: 255

tilt:
  ID: 2
  Baud_Rate: 3
  Return_Delay_Time: 0
  Drive_Mode: 0
  Velocity_Limit: 131
  Min_Position_Limit: 1274
  Max_Position_Limit: 2822
  Secondary_ID: 255

tilt_shadow:
  ID: 3
  Baud_Rate: 3
  Return_Delay_Time: 0
  Drive_Mode: 1
  Velocity_Limit: 131
  Min_Position_Limit: 1274
  Max_Position_Limit: 2822
  Secondary_ID: 2
